---
title: "Confusion Matrix on Predictions with RFM Labels"
output:
  html_document:
    df_print: paged
---

```{r, warning=FALSE, include=FALSE}
library(caret)
library(dplyr)
library(doParallel)

```


## Confusion Matrix for GBM model
```{r}

# Read the predictions dataframe
ecomdata<-read.csv("RFM_new/gradient-boosting.csv")
registerDoParallel(detectCores()-1)

# Plot confusion matrix
(cm=confusionMatrix(as.factor(ecomdata$predict), as.factor(ecomdata$is_purchased)))
table <- as.data.frame(cm$table)
plotTable <- table %>%
  mutate(goodbad = ifelse(table$Prediction == table$Reference, "good", "bad")) %>%
  group_by(Reference) %>%
  mutate(prop = Freq/sum(Freq))

# fill alpha relative to sensitivity/specificity by proportional outcomes within reference groups (see dplyr code above as well as original confusion matrix for comparison)
ggplot(data = plotTable, mapping = aes(x = Reference, y = Prediction, fill = goodbad, alpha = prop)) +
  geom_tile() +
  geom_text(aes(label = Freq), vjust = .5, fontface  = "bold", alpha = 1) +
  scale_fill_manual(values = c(good = "green", bad = "red")) +
  theme_bw() +
  xlim(rev(levels(table$Reference)))
```


## Confusion Matrix for LR model
```{r}

# Read the predictions dataframe
ecomdata<-read.csv("RFM_new/logisticRegression.csv")
registerDoParallel(detectCores()-1)

# Plot confusion matrix
(cm=confusionMatrix(as.factor(ecomdata$predict), as.factor(ecomdata$is_purchased)))
table <- as.data.frame(cm$table)
plotTable <- table %>%
  mutate(goodbad = ifelse(table$Prediction == table$Reference, "good", "bad")) %>%
  group_by(Reference) %>%
  mutate(prop = Freq/sum(Freq))

# fill alpha relative to sensitivity/specificity by proportional outcomes within reference groups (see dplyr code above as well as original confusion matrix for comparison)
ggplot(data = plotTable, mapping = aes(x = Reference, y = Prediction, fill = goodbad, alpha = prop)) +
  geom_tile() +
  geom_text(aes(label = Freq), vjust = .5, fontface  = "bold", alpha = 1) +
  scale_fill_manual(values = c(good = "green", bad = "red")) +
  theme_bw() +
  xlim(rev(levels(table$Reference)))
```



## Confusion Matrix for RF model
```{r}

# Read the predictions dataframe
ecomdata<-read.csv("RFM_new/random-forest.csv")
registerDoParallel(detectCores()-1)

# Plot confusion matrix
(cm=confusionMatrix(as.factor(ecomdata$predict), as.factor(ecomdata$is_purchased)))
table <- as.data.frame(cm$table)
plotTable <- table %>%
  mutate(goodbad = ifelse(table$Prediction == table$Reference, "good", "bad")) %>%
  group_by(Reference) %>%
  mutate(prop = Freq/sum(Freq))

# fill alpha relative to sensitivity/specificity by proportional outcomes within reference groups (see dplyr code above as well as original confusion matrix for comparison)
ggplot(data = plotTable, mapping = aes(x = Reference, y = Prediction, fill = goodbad, alpha = prop)) +
  geom_tile() +
  geom_text(aes(label = Freq), vjust = .5, fontface  = "bold", alpha = 1) +
  scale_fill_manual(values = c(good = "green", bad = "red")) +
  theme_bw() +
  xlim(rev(levels(table$Reference)))
```




## Confusion Matrix for Stacked model
```{r}

# Read the predictions dataframe
ecomdata<-read.csv("RFM_new/RFMstacked_ensemble.csv")
registerDoParallel(detectCores()-1)

# Plot confusion matrix
(cm=confusionMatrix(as.factor(ecomdata$predict), as.factor(ecomdata$is_purchased)))
table <- as.data.frame(cm$table)
plotTable <- table %>%
  mutate(goodbad = ifelse(table$Prediction == table$Reference, "good", "bad")) %>%
  group_by(Reference) %>%
  mutate(prop = Freq/sum(Freq))

# fill alpha relative to sensitivity/specificity by proportional outcomes within reference groups (see dplyr code above as well as original confusion matrix for comparison)
ggplot(data = plotTable, mapping = aes(x = Reference, y = Prediction, fill = goodbad, alpha = prop)) +
  geom_tile() +
  geom_text(aes(label = Freq), vjust = .5, fontface  = "bold", alpha = 1) +
  scale_fill_manual(values = c(good = "green", bad = "red")) +
  theme_bw() +
  xlim(rev(levels(table$Reference)))
```
